### ISSUE TITLE
(fix) Buttons unresponsive on Mobile

### ISSUE THREAD

**Issue by flooreyes** [sauce-community/landing-page#15]
Most buttons not responding to touch on mobile. The nav links on the mobile menu are responding fine, but most all other buttons in the page content do not. Could potentially be due to buttons and anchors being wrapped in divs?
see: https://stackoverflow.com/questions/50581836/html-button-not-working-in-mobile-device

Below are all buttons that should be able to be tapped on mobile that are not.

Hero Section:
-Launch App
-Join Sauce DAO

About Section:
-Learn More

Contact Section:
-All 4 Inputs 
-Submit

Resources Section:
-Github
-White Paper
-Join Now
-Apply Now
-Snapshot
-Governance Discussion
-Buy Sauce

Footer:
- all footer links and social icons

**Comment by ghost** [comment]
Issue is caused by the div class on line 48 covering other elements in index.html. Not sure how to fix.

**Comment by ghost** [comment]
Might be something to do with line 832 in style.css. If I delete the .nav-wrapper css section the formatting for the menu goes away (it semi-breaks) but the buttons are clickable again.

**Comment by flooreyes** [comment]
got it! just needed pointer-events: none on the wrapper and pointer-events: all when the menu's open.
